version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - portfolio-network 

  portfolio-api:
    build: 
      context: ./portfolio-api
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    depends_on:
      - rabbitmq

    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
